language: c
compiler:
    - gcc
sudo: required
services:
    - docker

matrix:
    include:
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-16.04 COMPILER=gcc-5
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-16.04 COMPILER=clang-4
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-16.04 COMPILER=clang-5
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-18.04 COMPILER=clang-4
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-18.04 COMPILER=clang-5
        - os: linux
          compiler: clang
          env: BUILD_OS=ubuntu-18.04 COMPILER=clang-6
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc-5
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc-6
        - os: linux
          compiler: gcc
          env: BUILD_OS=ubuntu-18.04 COMPILER=gcc-7
        - os: linux
          compiler: gcc
          env: BUILD_OS=arch COMPILER=gcc-5
        - os: linux
          compiler: gcc
          env: BUILD_OS=arch COMPILER=gcc-8 GEN=gen-8
        - os: linux
          compiler: gcc
          env: BUILD_OS=arch COMPILER=gcc-8 GEN=gen-9
        - os: linux
          compiler: clang
          env: BUILD_OS=arch COMPILER=clang-6
        - os: linux
          compiler: gcc
          env: BUILD_OS=fedora-27 COMPILER=gcc-7
        - os: linux
          compiler: clang
          env: BUILD_OS=fedora-27 COMPILER=clang-5
        - os: linux
          compiler: gcc
          env: BUILD_OS=fedora-28 COMPILER=gcc-8
        - os: linux
          compiler: clang
          env: BUILD_OS=fedora-28 COMPILER=clang-6

script: ./scripts/run-build.sh

